String.prototype.format=function(){var formatted=this;for(var i=0;i<arguments.length;i++){var regexp=new RegExp('\\{'+i+'\\}','gi');formatted=formatted.replace(regexp,arguments[i]);}
return formatted;};String.prototype.successor=function(){var str=this,alphabet='abcdefghijklmnopqrstuvwxyz',length=alphabet.length,result=str,i=str.length;while(i>=0){var last=str.charAt(--i),next='',carry=false;if(isNaN(last)){index=alphabet.indexOf(last.toLowerCase());if(index===-1){next=last;carry=true;}
else{var isUpperCase=last===last.toUpperCase();next=alphabet.charAt((index+1)%length);if(isUpperCase){next=next.toUpperCase();}
carry=index+1>=length;if(carry&&i===0){var added=isUpperCase?'A':'a';result=added+next+result.slice(1);break;}}}
else{next=+last+1;if(next>9){next=0;carry=true;}
if(carry&&i===0){result='1'+next+result.slice(1);break;}}
result=result.slice(0,i)+next+result.slice(i+1);if(!carry){break;}}
return result;}
String.prototype.removeHtmlTag=function(){var tmp=document.createElement('DIV');tmp.innerHTML=this;return tmp.textContent||tmp.innerText||'';}
String.prototype.startWith=function(value){return this.indexOf(value)==0;}
String.prototype.bool=function(){return(/^true$/i).test(this);};String.prototype.trim=function(){return this.replace(/(?:(?:^|\n)\s+|\s+(?:$|\n))/g,'').replace(/\s+/g,' ');};String.prototype.isEmpty=function(){return this.length==0;};String.prototype.isNullOrEmpty=function(){return!this;};String.prototype.isLastTrimEmpty=function(){return this.trim().length==0;};String.prototype.isNullOrWhiteSpace=function(){return this.isNullOrEmpty()||this.isLastTrimEmpty();};String.prototype.contains=function(){return arguments&&arguments[0]&&this.indexOf(arguments[0])>-1;};String.prototype.count=function(ch){return this.split(ch).length-1;};String.prototype.hasHtmlTags=function(){var r=false,e=document.createElement('div');e.innerHTML=this;for(var c=e.childNodes,i=c.length;i--;){if(c[i].nodeType==1){r=true;break;}}
return r;};String.prototype.replaceAll=function(from,to){return this.split(from).join(to);};String.prototype.toUpperCaseFirstChar=function(){var sourceWord=this;var fullWord="";if(sourceWord){var lstWord=sourceWord.split(" ");for(var i=0;i<lstWord.length;i++){var word=lstWord[i];var f_word=word.substr(0,1);var l_word=word.substr(1,word.length);f_word=f_word.toUpperCase();word=f_word+l_word;fullWord+=word+" "}}
return fullWord.trim();};String.prototype.toLowerCaseFirstChar=function(){var sourceWord=this;var fullWord="";if(sourceWord){var lstWord=sourceWord.split(" ");for(var i=0;i<lstWord.length;i++){var word=lstWord[i];var f_word=word.substr(0,1);var l_word=word.substr(1,word.length);f_word=f_word.toLowerCase();word=f_word+l_word;fullWord+=word+" "}}
return fullWord.trim();};String.prototype.processXXS=function(){return this.replaceAll('<sc','&lt;sc').replaceAll('pt>','pt&gt;').replaceAll('Pt>','pt&gt;').replaceAll('PT>','pt&gt;').replaceAll('pT>','pt&gt;').replaceAll('</sc','&lt;/sc').replaceAll('</Sc','&lt;/sc').replaceAll('</SC','&lt;/sc').replaceAll('</sC','&lt;/sc').replaceAll('<Sc','&lt;sc').replaceAll('<SC','&lt;sc').replaceAll('<sC','&lt;sc').replaceAll('<in','&lt;in').replaceAll('<In','&lt;in').replaceAll('<iN','&lt;in').replaceAll('<IN','&lt;in').replaceAll('<sel','&lt;sel').replaceAll('<Sel','&lt;sel').replaceAll('<sEl','&lt;sel').replaceAll('<seL','&lt;sel').replaceAll('<Sel','&lt;sel').replaceAll('<SeL','&lt;sel').replaceAll('<sEL','&lt;sel');}
String.prototype.processXSS=function(){return this.replaceAll('<sc','&lt;sc').replaceAll('pt>','pt&gt;').replaceAll('Pt>','pt&gt;').replaceAll('PT>','pt&gt;').replaceAll('pT>','pt&gt;').replaceAll('</sc','&lt;/sc').replaceAll('</Sc','&lt;/sc').replaceAll('</SC','&lt;/sc').replaceAll('</sC','&lt;/sc').replaceAll('<Sc','&lt;sc').replaceAll('<SC','&lt;sc').replaceAll('<sC','&lt;sc').replaceAll('<in','&lt;in').replaceAll('<In','&lt;in').replaceAll('<iN','&lt;in').replaceAll('<IN','&lt;in').replaceAll('<sel','&lt;sel').replaceAll('<Sel','&lt;sel').replaceAll('<sEl','&lt;sel').replaceAll('<seL','&lt;sel').replaceAll('<Sel','&lt;sel').replaceAll('<SeL','&lt;sel').replaceAll('<sEL','&lt;sel').replaceAll('<im','&lt;im').replaceAll('<iM','&lt;iM').replaceAll('<Im','&lt;Im').replaceAll('<IM','&lt;IM').replaceAll('<b','&lt;b').replaceAll('<B','&lt;B').replaceAll('b>','b&gt;').replaceAll('B>','B&gt;');}
String.prototype.UpperCaseFirstLetter=function(){var strName=this;if(strName&&strName.charAt(0)!=" "){strName=strName.charAt(0).toUpperCase()+strName.slice(1);if(strName.length>2){var lastChar=strName.slice(strName.length-2);var firstChar=strName.substr(0,strName.length-2);if(lastChar.charAt(0)===" ")
if(lastChar.slice(1)===" "){lastChar=lastChar.charAt(0);}else{var strLastOfSpace=strName.substr(strName.lastIndexOf(" "),strName.length);lastChar=lastChar.charAt(0)+strLastOfSpace.charAt(1).toUpperCase()+strLastOfSpace.slice(2);}
strName=firstChar+lastChar;}}else{strName=strName.trim();}
return strName;}
if(!Array.prototype.addRange){Array.prototype.addRange=function(a){var m=this;a.forEach(function(o,i){m.push(o);});};}
if(!Array.prototype.intersect){Array.prototype.intersect=function(destination){var source=this;var result=$(source).not($(source).not(destination));return result};};Array.prototype.contains=function(value){return this.indexOf(value)>-1;};if(!Array.prototype.first){Array.prototype.first=function(){var me=this,ret;if(me.length>0){ret=me[0];}
return ret;};};if(!Array.prototype.last){Array.prototype.last=function(){var me=this,ret;if(me.length>0){ret=me[me.length-1];}
return ret;};};if(!Array.prototype.insert){Array.prototype.insert=function(index,value){this.splice(index,0,value);};}
if(!Array.prototype.remove){Array.prototype.remove=function(removeItem){var source=this;source=$.grep(source,function(s){return s!=removeItem;});return source;}};if(!Array.prototype.distinct){Array.prototype.distinct=function(){var a=this,i,curItem,r=[];for(i=0;i<a.length;i++){curItem=a[i];if(r.indexOf(curItem)==-1){r.push(curItem);}}
return r;};}
if(!Array.prototype.sortObject){Array.prototype.sortObject=function(){if(arguments.length>0){var fn=function(a,b,fields,index){var r=0,d=fields[index].split(' '),f=d.first(),v=d.length>1&&d.last().toLowerCase()=='desc'?-1:1,fnCompare=function(field){var res=0,va=undefined,vb=undefined;field.split('.').forEach(function(fi){va=va==undefined?a[fi]:va[fi];vb=vb==undefined?b[fi]:vb[fi];});if(va<vb){res=-1*v;}else if(va>vb){res=v;}
return res;};r=fnCompare(f);if(r==0&&fields.length>index+1){r=fn(a,b,fields,index+1);}
return r;}
var fs=arguments;return this.sort(function(a,b){return fn(a,b,fs,0);});}else{throw 'fields invalid';}};};Array.prototype.sumByNumberField=function(field){let sum=0;this.filter(function(x){sum+=x[field];});return sum;};Array.prototype.removeAt=function(index){this.splice(index,1);};Array.prototype.distinctObject=function(fields){var fields=fields||'';var valueIndex=[];var result=[];var listField=fields.trim().split(';');this.filter(function(x){var value='';listField.filter(function(field){value+=x[field];});if(!valueIndex.contains(value)){valueIndex.push(value);result.push(x);}});return result;};Array.prototype.getListByKey=function(key,value){var result=[];this.filter(function(x){if(x[key]==value){result.push(x);}});return result;};Array.prototype.removeByKey=function(key,value){var result=[];this.filter(function(x){if(x[key]!=value){result.push(x);}});return result;};Array.prototype.mapValuesByKey=function(key){return this.map(function(item){return item[key];});};Math.roundNumber=function(value,decimalNumber){if(decimalNumber){return Math.round(value*decimalNumber*10)/(decimalNumber*10);}else{return value;}}
Math.roundDigitNumber=function(value,decimalNumber){if(decimalNumber){return Math.round(value*Math.pow(10,decimalNumber))/(Math.pow(10,decimalNumber));}else{return value;}}
Date.prototype.addSeconds=function(m){var tempDate=new Date(this.getTime());tempDate.setTime(this.getTime()+(m*1000));return tempDate;}
Date.prototype.addMinutes=function(m){var tempDate=new Date(this.getTime());tempDate.setTime(this.getTime()+(m*60*1000));return tempDate;}
Date.prototype.addHours=function(h){var tempDate=new Date(this.getTime());tempDate.setTime(this.getTime()+(h*60*60*1000));return tempDate;}
Date.prototype.addDays=function(day){var tempDate=new Date(this.getTime());tempDate.setDate(this.getDate()+day);return tempDate;}
Date.prototype.addMonths=function(month){var tempDate=new Date(this.getTime());tempDate.setMonth(this.getMonth()+month);return tempDate;}
Date.prototype.compareDate=function(date2,isDateTimeCompare){if(date2){if(isDateTimeCompare===1){return this.getTime()-date2.getTime();}else{tempDateCurent=new Date(this.getFullYear(),this.getMonth(),this.getDate());tempDateCompare=new Date(date2.getFullYear(),date2.getMonth(),date2.getDate());return tempDateCurent.getTime()-tempDateCompare.getTime();}}else{return 1;}}
Date.prototype.resetTime=function(){this.setHours(0);this.setMinutes(0);this.setSeconds(0);this.setMilliseconds(0);return this;}
Number.prototype.moneyFormat=function(){var self=this,moneyType=' đ',value=null;if(self){value=self.toString().replace(/(\d)(?=(\d\d\d)+(?!\d))/g,"$1,")+moneyType;}
return value;}
function customProps(obj,ps){obj=obj||{};for(var i in ps){obj[i]=ps[i];}}
File.prototype.convertToBase64=function(callback){var reader=new FileReader();reader.onload=function(e){callback(e.target.result);}
reader.onerror=function(e){callback(null);}
reader.readAsDataURL(this);}