Ext.define('MISA.MessageBox',{extend:'Ext.window.Window',singleton:true,requires:['Ext.toolbar.Toolbar','Ext.form.field.Text','Ext.form.field.TextArea','Ext.button.Button','Ext.layout.container.Anchor','Ext.layout.container.HBox','Ext.ProgressBar'],alias:'widget.misamessagebox',OK:1,YES:2,NO:4,CANCEL:8,OKCANCEL:9,YESNO:6,YESNOCANCEL:14,INFO:Ext.baseCSSPrefix+'message-box-info',WARNING:Ext.baseCSSPrefix+'message-box-warning',QUESTION:Ext.baseCSSPrefix+'message-box-question',ERROR:Ext.baseCSSPrefix+'message-box-error',hideMode:'offsets',closeAction:'hide',resizable:false,scrollable:true,title:MISA.Resource.GlobalResource.ApplicationName,defaultMinWidth:400,defaultMaxWidth:600,defaultMinHeight:110,defaultMaxHeight:500,minWidth:null,maxWidth:null,minHeight:null,maxHeight:null,constrain:true,cls:[Ext.baseCSSPrefix+'message-box',Ext.baseCSSPrefix+'hidden-offsets','m-message-box'],layout:{type:'vbox',align:'stretch'},shrinkWrapDock:true,defaultTextHeight:75,minProgressWidth:250,minPromptWidth:250,buttonText:{ok:"Đồng ý",yes:"Có",no:"Không",cancel:"Hủy bỏ",},buttonIconCls:{ok:'m-icon-submit',yes:'m-icon-yes',no:'m-icon-no',cancel:'m-icon-disable',},buttonIds:['ok','yes','no','cancel'],titleText:{confirm:'Confirm',prompt:'Prompt',wait:'Loading...',alert:'Attention'},baseIconCls:Ext.baseCSSPrefix+'message-box-icon',ariaRole:'alertdialog',makeButton:function(btnIdx){var me=this,btnId=me.buttonIds[btnIdx];return new MISA.Control.MISAButton({handler:me.btnCallback,itemId:btnId,scope:me,cls:'abc2',text:me.buttonText[btnId],iconCls:me.buttonIconCls[btnId],minWidth:75,});},btnCallback:function(btn,event){var me=this,value,field;if(event&&event.type==='keydown'&&!event.isSpecialKey()){event.getTarget(null,null,true).on({keyup:function(e){me.btnCallback(btn,e);},single:true});return;}
if(me.cfg.prompt||me.cfg.multiline){if(me.cfg.multiline){field=me.textArea;}else{field=me.textField;}
value=field.getValue();field.reset();}
me.hide();me.userCallback(btn.itemId,value,me.cfg);},hide:function(){var me=this,cls=me.cfg?me.cfg.cls:'';me.progressBar.reset();if(cls){me.removeCls(cls);}
me.callParent(arguments);},constructor:function(cfg){var me=this;me.callParent(arguments);me.minWidth=me.defaultMinWidth=(me.minWidth||me.defaultMinWidth);me.maxWidth=me.defaultMaxWidth=(me.maxWidth||me.defaultMaxWidth);me.minHeight=me.defaultMinHeight=(me.minHeight||me.defaultMinHeight);me.maxHeight=me.defaultMaxHeight=(me.maxHeight||me.defaultMaxHeight);},initComponent:function(cfg){var me=this,baseId=me.id,i,button;me.title=me.title||'&#160;';me.iconCls=me.iconCls||'';me.topContainer=new Ext.container.Container({layout:'hbox',style:{overflow:'hidden'},items:[me.iconComponent=new Ext.Component({cls:me.baseIconCls,width:32}),me.promptContainer=new Ext.container.Container({flex:1,cls:'demo1',layout:{type:'vbox',align:'stretch'},items:[me.msg=new Ext.Component({id:baseId+'-msg',margin:'4 0 0 0',cls:me.baseCls+'-text m-messagebox-msg'}),me.textField=new Ext.form.field.Text({id:baseId+'-textfield',enableKeyEvents:true,listeners:{keydown:me.onPromptKey,scope:me}}),me.textArea=new Ext.form.field.TextArea({id:baseId+'-textarea',height:75})]})]});me.progressBar=new Ext.ProgressBar({id:baseId+'-progressbar',margin:'0 10 10 10'});me.items=[me.topContainer,me.progressBar];me.msgButtons=[];for(i=0;i<4;i++){button=me.makeButton(i);me.msgButtons[button.itemId]=button;me.msgButtons.push(button);}
me.bottomTb=new Ext.toolbar.Toolbar({id:baseId+'-toolbar',ui:'footer',dock:'bottom',padding:8,inactiveChildTabIndex:0,layout:{pack:'end'},items:[me.msgButtons[0],me.msgButtons[1],me.msgButtons[2],me.msgButtons[3]]});me.dockedItems=[me.bottomTb];me.on('close',me.onClose,me);me.callParent();},onClose:function(){var btn=this.header.child('[type=close]');btn.itemId='cancel';this.btnCallback(btn);delete btn.itemId;},onPromptKey:function(textField,e){var me=this;if(e.keyCode===e.RETURN||e.keyCode===10){if(me.msgButtons.ok.isVisible()){me.msgButtons.ok.handler.call(me,me.msgButtons.ok);}else if(me.msgButtons.yes.isVisible()){me.msgButtons.yes.handler.call(me,me.msgButtons.yes);}}},reconfigure:function(cfg){var me=this,buttons=0,hideToolbar=true,oldButtonText=me.buttonText,resizer=me.resizer,header=me.header,headerCfg=header&&!header.isHeader,message=cfg&&(cfg.message||cfg.msg),resizeTracker,width,height,i,textArea,textField,msg,progressBar,msgButtons;me.updateButtonText();me.cfg=cfg=cfg||{};if(cfg.width){width=cfg.width;}
if(cfg.height){height=cfg.height;}
me.minWidth=cfg.minWidth||me.defaultMinWidth;me.maxWidth=cfg.maxWidth||me.defaultMaxWidth;me.minHeight=cfg.minHeight||me.defaultMinHeight;me.maxHeight=cfg.maxHeight||me.defaultMaxHeight;if(resizer){resizeTracker=resizer.resizeTracker;resizer.minWidth=resizeTracker.minWidth=me.minWidth;resizer.maxWidth=resizeTracker.maxWidth=me.maxWidth;resizer.minHeight=resizeTracker.minHeight=me.minHeight;resizer.maxHeight=resizeTracker.maxHeight=me.maxHeight;}
delete me.defaultFocus;if(cfg.defaultFocus){me.defaultFocus=cfg.defaultFocus;}
me.animateTarget=cfg.animateTarget||undefined;me.modal=cfg.modal!==false;me.setTitle(cfg.title||(headerCfg&&header.title)||me.title);me.setIconCls(cfg.iconCls||(headerCfg&&header.iconCls)||me.iconCls);if(Ext.isObject(cfg.buttons)){me.buttonText=cfg.buttons;buttons=0;}else{me.buttonText=cfg.buttonText||me.buttonText;buttons=Ext.isNumber(cfg.buttons)?cfg.buttons:0;}
buttons=buttons|me.updateButtonText();me.buttonText=oldButtonText;Ext.suspendLayouts();me.width=me.height=null;if(width||height){if(width){me.setWidth(width);}
if(height){me.setHeight(height);}}
me.hidden=false;if(!me.rendered){me.render(Ext.getBody());}
me.closable=cfg.closable!==false&&!cfg.wait;header=me.header;me.closable=false;if(header){header.child('[type=close]').setVisible(me.closable);if(!cfg.title&&!me.closable&&!cfg.iconCls){header.hide();}else{header.show();}}
me.liveDrag=!cfg.proxyDrag;me.userCallback=Ext.Function.bindCallback(cfg.callback||cfg.fn||Ext.emptyFn,cfg.scope||Ext.global);me.setIcon(cfg.icon);msg=me.msg;if(message){msg.setHtml(message);msg.show();}else{msg.hide();}
textArea=me.textArea;textField=me.textField;if(cfg.prompt||cfg.multiline){me.multiline=cfg.multiline;if(cfg.multiline){textArea.setValue(cfg.value);textArea.setHeight(cfg.defaultTextHeight||me.defaultTextHeight);textArea.show();textField.hide();me.defaultFocus=textArea;}else{textField.setValue(cfg.value);textArea.hide();textField.show();me.defaultFocus=textField;}}else{textArea.hide();textField.hide();}
progressBar=me.progressBar;if(cfg.progress||cfg.wait){progressBar.show();me.updateProgress(0,cfg.progressText);if(cfg.wait===true){progressBar.wait(cfg.waitConfig);}}else{progressBar.hide();}
msgButtons=me.msgButtons;for(i=0;i<4;i++){if(buttons&Math.pow(2,i)){if(!me.defaultFocus){me.defaultFocus=msgButtons[i];}
msgButtons[i].show();hideToolbar=false;}else{msgButtons[i].hide();}}
if(hideToolbar){me.bottomTb.hide();}else{me.bottomTb.show();}
me.updateButtonIconCls(cfg);Ext.resumeLayouts(true);},updateButtonText:function(){var me=this,buttonText=me.buttonText,buttons=0,btnId,btn;for(btnId in buttonText){if(buttonText.hasOwnProperty(btnId)){btn=me.msgButtons[btnId];if(btn){if(me.cfg&&me.cfg.buttonText){buttons=buttons|Math.pow(2,Ext.Array.indexOf(me.buttonIds,btnId));}
if(btn.text!=buttonText[btnId]){btn.setText(buttonText[btnId]);}}}}
return buttons;},updateButtonIconCls:function(cfg){var me=this,buttonIconCls=me.getButtonIconCls(cfg),buttons=0,btnId,btn;for(btnId in buttonIconCls){if(buttonIconCls.hasOwnProperty(btnId)){btn=me.msgButtons[btnId];if(btn){if(me.cfg&&me.cfg.buttonIconCls){buttons=buttons|Math.pow(2,Ext.Array.indexOf(me.buttonIds,btnId));}
if(btn.iconCls!=buttonIconCls[btnId]){btn.setIconCls(buttonIconCls[btnId]);}}}}
return buttons;},getButtonIconCls:function(cfg){var me=this,objCls={};Ext.apply(objCls,me.buttonIconCls);Ext.apply(objCls,cfg.buttonIconCls);return objCls;},show:function(cfg){var me=this,visibleFocusables;cfg=cfg||{};if(Ext.Component.layoutSuspendCount){Ext.on({resumelayouts:function(){me.show(cfg);},single:true});return me;}
me.reconfigure(cfg);if(cfg.cls){me.addCls(cfg.cls);}
visibleFocusables=me.query('textfield:not([hidden]),textarea:not([hidden]),button:not([hidden])');me.preventFocusOnActivate=!visibleFocusables.length;me.hidden=true;me.callParent();return me;},onShow:function(){this.callParent(arguments);this.center();if(this.defaultFocus&&this.defaultFocus.el&&this.defaultFocus.el.dom){this.defaultFocus.el.dom.focus();}},updateText:function(text){this.msg.setHtml(text);},setIcon:function(icon,width,height){var me=this,iconCmp=me.iconComponent,cls=me.messageIconCls;if(cls){iconCmp.removeCls(cls);}
if(icon){iconCmp.show();if(width||height){iconCmp.setSize(width||iconCmp.getWidth(),height||iconCmp.getHeight());}
iconCmp.addCls(Ext.baseCSSPrefix+'dlg-icon');iconCmp.addCls(me.messageIconCls=icon);}else{iconCmp.removeCls(Ext.baseCSSPrefix+'dlg-icon');iconCmp.hide();}
return me;},updateProgress:function(value,progressText,message){this.progressBar.updateProgress(value,progressText);if(message){this.updateText(message);}
return this;},onEsc:function(){if(this.closable!==false){this.callParent(arguments);}},confirm:function(cfg,message,title,fn,scope){if(Ext.isString(cfg)){cfg={title:title,message:message,buttons:this.YESNO,callback:fn,scope:scope};}
if(!Ext.isEmpty(message)&&Ext.isEmpty(title)){cfg.cls='msgbox-notitle';}
return this.show(cfg);},prompt:function(title,message,fn,scope,multiline,value){if(Ext.isString(title)){title={prompt:true,title:title,minWidth:this.minPromptWidth,message:message,buttons:this.OKCANCEL,callback:fn,scope:scope,multiline:multiline,value:value};}
return this.show(title);},wait:function(message,title,config){if(Ext.isString(message)){message={title:title,message:message,closable:false,wait:true,modal:true,minWidth:this.minProgressWidth,waitConfig:config};}
return this.show(message);},alert:function(title,message,fn,scope){if(Ext.isString(title)){title={title:title,message:message,buttons:this.OK,fn:fn,scope:scope,minWidth:this.minWidth};}
return this.show(title);},progress:function(title,message,progressText){if(Ext.isString(title)){title={title:title,message:message,progress:true,progressText:progressText};}
return this.show(title);},showError:function(msg,config){var me=this;config=config||{};config.message=msg;config.buttons=config['buttons']||Ext.Msg.OK;config.icon=config['icon']||Ext.Msg.ERROR;me.show(config);},showWarning:function(msg,config,title){var me=this;config=config||{};config.message=msg||config[msg];config.title=title;config.buttons=config['buttons']||Ext.Msg.OK;me.show(config);},showWarning:function(msg,config,title,callbackFunc){var me=this;config=config||{};config.message=msg||config[msg];config.title=title;config.buttons=config['buttons']||Ext.Msg.OK;config.callback=callbackFunc;if(!Ext.isEmpty(msg)&&Ext.isEmpty(title)){config.cls='msgbox-notitle';}
me.show(config);},showConfirm:function(msg,title,callbackFunc,scope,config){var me=this;config=config||{};config.message=msg||config[msg];config.title=title;config.callback=callbackFunc||config[callbackFunc];config.scope=scope||config[scope];config.buttons=config['buttons']||Ext.Msg.YESNO;if(!Ext.isEmpty(config.message)&&Ext.isEmpty(config.title)){config.cls='msgbox-notitle';}
me.show(config);},showOkCancel:function(msg,callbackFunc,scope,config){var me=this;config=config||{};config.message=msg||config[msg];config.callback=callbackFunc||config[callbackFunc];config.scope=scope||config[scope];config.buttons=config['buttons']||Ext.Msg.OKCANCEL;config.icon=config['icon']||Ext.Msg.QUESTION;config.cls='msgbox-notitle';me.show(config);},showConfirmOverride:function(msg,title,callbackFunc,scope,config){var me=this;config=config||{};config.message=msg||config[msg];config.title=title;config.callback=callbackFunc||config[callbackFunc];config.scope=scope||config[scope];config.buttons=config['buttons']||Ext.Msg.OKCANCEL;config.icon=config['icon']||Ext.Msg.QUESTION;if(!Ext.isEmpty(config.message)&&Ext.isEmpty(config.title)){config.cls='msgbox-notitle';}
me.show(config);},showYesNoCancel:function(msg,callbackFunc,scope,config){var me=this;config=config||{};config.message=msg||config[msg];config.callback=callbackFunc||config[callbackFunc];config.scope=scope||config[scope];config.buttons=config['buttons']||Ext.Msg.YESNOCANCEL;config.icon=config['icon']||Ext.Msg.QUESTION;config.cls='msgbox-notitle';me.show(config);},showWarningYesNo:function(msg,callbackFunc,scope,config){var me=this;config=config||{};config.message=msg||config[msg];config.callback=callbackFunc||config[callbackFunc];config.scope=scope||config[scope];config.buttons=config['buttons']||Ext.Msg.YESNO;config.icon=config['icon']||Ext.Msg.WARNING;config.cls='msgbox-notitle';me.show(config);},showWarningYesNoCancel:function(title,msg,callbackFunc,scope,config){var me=this;config=config||{};config.message=msg||config[msg];config.title=title;config.callback=callbackFunc||config[callbackFunc];config.scope=scope||config[scope];config.buttons=config['buttons']||Ext.Msg.YESNOCANCEL;me.show(config);},});