Ext.define('MISA.Control.MISAComboboxData',{xtype:'misacomboboxdata',extend:'MISA.Control.MISACombobox',alias:'widget.misacomboboxdata',autoLoadData:false,pagingData:false,isSetDataToStoreDone:false,anyMatch:true,sourceData:null,customConfig:function(config){config.queryCaching=false;},beforeQuery:function(queryPlan){var me=this;if(me.isSetDataToStoreDone===true){me.queryMode='local';}else{me.queryMode='remote';}
return me.callParent(arguments);},doLocalQuery:function(queryPlan){var me=this,queryString=queryPlan.query,filters=me.getStore().getFilters(),filter=me.queryFilter;me.queryFilter=null;me.changingFilters=true;filters.beginUpdate();if(filter){filters.remove(filter);}
filter=me.queryFilter=new Ext.util.Filter({id:me.id+'-filter',anyMatch:me.anyMatch,caseSensitive:me.caseSensitive,root:'data',property:me.displayField,value:me.enableRegEx?new RegExp(queryString):queryString,cbo:me,filterFields:!Ext.isArray(me.filterFields)?me.filterFields.split('|'):me.filterFields,filterFn:function(item){var me=this,anyMatch=!!me.getAnyMatch(),exact=!!me.getExactMatch(),value=me.getValue(),matcher=Ext.String.createRegex(value,!anyMatch,!anyMatch&&exact,!me.getCaseSensitive());var root=this._root;var dataItem=(root===null)?item:item[root];var fnTest=function(data){var bResultFnTest=false;for(var i=0;i<me.filterFields.length;i++){var val=data[me.filterFields[i]];if(matcher?matcher.test(val):(val===null)){bResultFnTest=true;break;}}
return bResultFnTest;}
var fnFilterCycle=function(data){var bResultfnFilterCycle=false;var lstSubItem;if((data.hasOwnProperty('MISACodeID')&&!Ext.isEmpty(data.MISACodeID))||(data.hasOwnProperty('MISACode')&&!Ext.isEmpty(data.MISACode))){if(data.hasOwnProperty('MISACodeID')&&!Ext.isEmpty(data.MISACodeID)){lstSubItem=me.cbo.sourceData.filter(function(f){return f.MISACodeID&&f.MISACodeID.startsWith(data.MISACodeID);});}
else if(data.hasOwnProperty('MISACode')&&!Ext.isEmpty(data.MISACode)){lstSubItem=me.cbo.sourceData.filter(function(f){return f.MISACode&&f.MISACode.startsWith(data.MISACode);});}
if(Ext.isArray(lstSubItem)){for(var i=0;i<lstSubItem.length;i++){bResultfnFilterCycle=fnTest(lstSubItem[i]);if(bResultfnFilterCycle){break;}}}}else if(data.hasOwnProperty('ParentID')){bResultfnFilterCycle=fnTest(data);if(bResultfnFilterCycle===false){lstSubItem=me.cbo.sourceData.filter(function(f){return f.ParentID===data[me.cbo.valueField];});if(Ext.isArray(lstSubItem)){for(var i=0;i<lstSubItem.length;i++){bResultfnFilterCycle=fnTest(lstSubItem[i]);if(bResultfnFilterCycle){break;}else{bResultfnFilterCycle=fnFilterCycle(lstSubItem[i]);}}}}}
return bResultfnFilterCycle;}
var bResult=false;if(me.cbo.isTreeDisplay){bResult=fnFilterCycle(dataItem);}else{bResult=fnTest(dataItem);}
return bResult;},});filters.add(filter);var picker=me.getPicker(),nm=picker.getNavigationModel();if(nm.record){nm.record=null;}
if(nm.recordIndex){nm.recordIndex=null;}
filters.endUpdate();me.changingFilters=false;var tmpAutoSelect=me.autoSelect;if(me.isTreeDisplay){me.autoSelect=false;}
if(me.store.getCount()||me.getPicker().emptyText){me.expand();me.setHighlightedItemByValue(me.getRawValue());}else{me.collapse();}
me.afterQuery(queryPlan);me.autoSelect=tmpAutoSelect;},setHighlightedItemByValue:function(value){var me=this;if(me.isTreeDisplay){var items=me.getStore().data.items;var filterFields=!Ext.isArray(me.filterFields)?me.filterFields.split('|'):me.filterFields;for(var i=0;i<items.length;i++){var data=items[i].data;for(var j=0;j<filterFields.length;j++){var val=data[filterFields[j]]+"";if(val.toLowerCase().contains(value.toLowerCase())){me.setHighlightedItemByIndex(i);return;}}}}},setHighlightedItemByIndex:function(recordIndex){var me=this,items=me.getStore().data.items,picker=me.getPicker();if(recordIndex>-1&&recordIndex<me.getStore().count()&&picker&&picker.isVisible()){me.clearInvalid();var nm=picker.getNavigationModel(),pitems=nm.view.all;if(pitems.getCount()>recordIndex){nm.setPosition(recordIndex);}else{var iv=setInterval(function(){if(pitems.getCount()-1>=recordIndex){clearInterval(iv);nm.setPosition(recordIndex);}},50);}}},onFieldMutation:function(e){var me=this,key=e.getKey(),isDelete=key===e.BACKSPACE||key===e.DELETE,rawValue=me.inputEl.dom.value,len=rawValue.length;if(key!==e.TAB){me.lastKey=key;if(len&&(e.type!=='keyup'||(!e.isSpecialKey()||isDelete))){me.doQueryTask.delay(me.queryDelay);}else{if(!len&&(!key||isDelete)){if(!me.multiSelect){me.value=null;me.displayTplData=undefined;}
me.collapse();if(me.queryFilter){me.changingFilters=true;me.store.removeFilter(me.queryFilter,true);me.changingFilters=false;}}
me.callParent([e]);}}},getProxyReaderResponseData:function(response,jsonReader){var me=this;if(response&&response.responseText){var obj=Ext.decode(response.responseText).d;if(obj.Status){var value=Ext.decode(obj.Data),data={};if(value&&Ext.isArray(value.Data)){data[jsonReader._successProperty]=true;data[jsonReader._rootProperty]=value.Data;data[jsonReader._totalProperty]=value.TotalCount;}
me.fireEvent('loadReponseData',me,value.Data);me.isSetDataToStoreDone=true;me.sourceData=value.Data;return data;}
else{return jsonReader.createReadError(obj.Message);}}},onFocusLeave:function(e){var me=this;if(e.fromComponent&&(me.picker&&e.fromComponent.up("#"+me.picker.id)===me.picker)){return;}
me.prepareRecord();me.collapse();me.callParent([e]);},getValue:function(){var me=this,value=me.callParent(arguments);if(me.autoLoadData&&me.isSetDataToStoreDone!==true&&me.originalValue!==undefined){value=me.originalValue;}
return value;},prepareRecord:function(){var me=this;if(me.forceSelection){if(!me.multiSelect){var sRawValue=me.getRawValue();if(!Ext.isEmpty(sRawValue)){var rec=me.getRecordHighlightedItem();if(rec){if(rec.data[me.displayField].toLowerCase()===sRawValue.toLowerCase()){if(!me.allowSelectSeperator&&rec.data.IsSperator===true){me.clearValue();}else{me.setValue(rec);}}else{me.clearValue();}}else{if(me.store){var rec=me.store.data.items.find(function(r){var sDisplay=r.data[me.displayField];var sValue=r.data[me.valueField];if(sDisplay){return sDisplay.toLowerCase()===sRawValue.toLowerCase()&&sValue==me.getValue();}else{return false;}});if(rec===undefined){rec=me.store.data.items.find(function(r){var sDisplay=r.data[me.displayField];var sValue=r.data[me.valueField];if(sDisplay){return sDisplay.toLowerCase()===sRawValue.toLowerCase();}else{return false;}});}
if(rec){if(!me.allowSelectSeperator&&rec.data.IsSperator===true){me.clearValue();}else{me.setValue(rec.get(me.valueField));}}else{me.clearValue();}}else if(me.sourceData){var item=me.sourceData.find(function(r){var sValue=r[me.displayField];if(sValue){return sValue.toLowerCase()===sRawValue.toLowerCase();}else{return false;}});if(item){if(item[me.valueField]!==me.getValue()){if(!me.allowSelectSeperator&&rec.data.IsSperator===true){me.clearValue();}else{me.setValue(item[me.valueField]);}}}else{me.clearValue();}}}}}}}});