Ext.define('MISA.Control.MISAComboBoxTree',{xtype:'misacomboboxtree',extend:'MISA.Control.MISAComboboxData',alias:'widget.misacomboboxtree',isTreeDisplay:true,selectOnFocus:false,editable:false,filterable:true,queryDelay:10,minChars:0,initComponent:function(){var me=this;me.callParent(arguments);me.doFilterTask=new Ext.util.DelayedTask(me.runFilter,me);},afterRender:function(){var me=this;me.callParent(arguments);var store=me.getStore();if(store&&!store.isLoading()){me.lastQuery="";store.load();}
if(me.inputEl){me.inputEl.dom.readOnly=true;}},focus:function(){var me=this;if(me.picker&&me.picker.inputSearchField){me.picker.inputSearchField.focus();}else{me.callParent(arguments);}},setReadOnly:function(isReadOnly){},createPicker:function(){var me=this,picker,pickerCfg=Ext.apply({xtype:'boundlist',pickerField:me,selectionModel:me.pickerSelectionModel,floating:true,hidden:true,store:me.getPickerStore(),displayField:me.displayField,preserveScrollOnRefresh:true,pageSize:me.pageSize,tpl:me.tpl,isCreateSearchField:true,},me.listConfig,me.defaultListConfig);picker=me.picker=Ext.widget(pickerCfg);if(me.pageSize){picker.pagingToolbar.on('beforechange',me.onPageChange,me);}
if(!picker.initialConfig.maxHeight){picker.on({beforeshow:me.onBeforePickerShow,scope:me});}
picker.getSelectionModel().on({beforeselect:me.onBeforeSelect,beforedeselect:me.onBeforeDeselect,scope:me});picker.getNavigationModel().navigateOnSpace=false;picker.cls=picker.cls||'';picker.cls+=' '+me.cls;return picker;},getInputTextValue:function(){var me=this,query=null;if(me.picker&&me.picker.inputSearchField){query=me.picker.getSearchValue();}
return query;},onSearchFieldChanged:function(sender,newValue,oldValue){var me=this;me.doFilterTask.delay(me.queryDelay,me.runFilter,me,[true]);},runFilter:function(isSearchField){var me=this,matchItems=[];if(!me.filterable&&!isSearchField){return;}
var store=me.getStore(),filters=store.getFilters(),filter=me.queryFilter,query=me.getInputTextValue()||'';var fnMatch=function(item){var displayField=me.displayField,valueField=me.valueField;if(displayField&&item.get(displayField)&&item.get(displayField).toString().toLowerCase().contains(query.toLowerCase())){return true;}
if(valueField&&item.get(displayField)&&item.get(displayField).toString().toLowerCase().contains(query.toLowerCase())){return true;}}
var fnFilterFlat=function(){store.data.items.filter(function(item){if(fnMatch(item)){fnFilterCycle(item);}});}
var fnFilterCycle=function(child){if(matchItems.indexOf(child)<0){matchItems.push(child);}
if(child&&child.data["ParentID"]){var p=store.getById(child.data["ParentID"]);fnFilterCycle(p);}}
if(filter){filters.remove(filter);}
filters.beginUpdate();me.changingFilters=true;if(query){fnFilterFlat();filter=me.queryFilter=new Ext.util.Filter({filterFn:function(i){if(matchItems.indexOf(i)>=0){return true;}}});filters.add(filter);}
filters.endUpdate();me.changingFilters=false;},getPicker:function(){if(!this.picker){this.listConfig=this.listConfig||{};this.picker=this.createPicker();if(this.multiSelect&&this.selectionMode=="checkbox"){this.picker.overItemCls='';this.picker.selectedItemCls='x-mcombo-item-checked';this.picker.tpl.getTreeNodeLevel=Ext.Function.bind(function(values){if(values.Grade){value=values.Grade;}
else
if(values.MISACodeID){value=values.MISACodeID.split('index.html').length-2;}
else if(values.MISACode){value=values.MISACode.split('index.html').length-2;}else{value=1;}
return "padding-left: "+((value-1)*20+20)+"px;";});this.picker.tpl.getTreeNodeClass=Ext.Function.bind(function(values){var record,selected,parent=(values.IsParent?'tree-parent':'tree-leaf');Ext.each(this.store.getRange(),function(r){if(r.get(this.valueField)==values[this.valueField]){record=r;return false;}},this);selected=record?this.picker.getSelectionModel().isSelected(record):false;if(selected){return " x-mcombo-item-checked "+parent;}
return " x-mcombo-item-unchecked "+parent;},this,[],true);};}
return this.picker;}});