Ext.define('MISA.Control.MISAComboboxDemand',{xtype:'misacomboboxdemand',extend:'MISA.Control.MISACombobox',alias:'widget.misacomboboxdemand',lastValueToSearch:undefined,pagingData:true,customConfig:function(config){config.queryMode='remote';config.autoLoadData=false;},initComponent:function(){var me=this;if(me.showPaging===false){me.pageSize=0;}else{if(me.pageSize===0){me.pageSize=10;}}
me.callParent(arguments);if(me.store){me.store.on('beforeload',me.onStoreBeforeLoad,me);}},beforeQuery:function(queryPlan){var me=this;if(me.showPaging===false&&me.store){me.store.page=1;me.store.loadCount=0;me.store.currentPage=1;}
return me.callParent(arguments);},doQuery:function(queryString,forceAll,rawQuery){var me=this,queryPlan=me.beforeQuery({query:queryString||'',rawQuery:rawQuery,forceAll:forceAll,combo:me,cancel:false});if(queryPlan!==false&&!queryPlan.cancel){if(me.queryCaching&&!me.checkTempRecord()&&me.lastValueToSearch===me.getRawValue()&&me.getRawValue()!==''){if(me.store&&me.store.getCount()===0){me.collapse();}else{me.expand();}
if(me.queryMode==='local'){me.doAutoSelect();}}
else{me.lastQuery=queryPlan.query;if(me.queryMode==='local'){me.doLocalQuery(queryPlan);}else{me.doRemoteQuery(queryPlan);}}}
return true;},checkTempRecord:function(record){var me=this,res=false,fn=function(r){return r.isTempRecord;}
if(record){res=fn(record);}else{var items=me.store.data.items;for(var i=0;i<items.length;i++){if(fn(items[i])){res=true;break;}}}
return res;},onStoreBeforeLoad:function(store,options){var me=this,filterFields=me.filterFields;if(filterFields){var arr=filterFields.split("|");if(arr&&arr.length>0){var filters={};arr.filter(function(a){var f=me.getFilterHeader(a);f.dataIndex=a;filters[a]=f;me.lastValueToSearch=f.value;});var p={"filterHeader":Ext.encode(filters)};options.setParams(p);}}},getFilterHeader:function(a){var me=this,value=me.inputEl.dom.value,fh=me.columnsConfig.filter(function(f){return f.DataField==a}).length>0?me.columnsConfig.filter(function(f){return f.DataField==a}).first():null;var filter={type:"string",op:me.getOperationFilter(fh),dataIndex:null,value:value,operand:"|",};return filter;},onBindStore:function(store,initial){var me=this;me.callParent(arguments);me.pickerSelectionModel.deselectOnContainerClick=false;},onFocusLeave:function(e){var me=this;if(e.fromComponent&&me.picker&&e.fromComponent.up("#"+me.picker.id)===me.picker){return;}
if(me.forceSelection){if(!me.multiSelect){var sRawValue=me.getRawValue();if(!Ext.isEmpty(sRawValue)){var rec=me.getRecordHighlightedItem();if(rec){if(rec.data[me.displayField].toLowerCase()===sRawValue.toLowerCase()){me.setValue(rec);}else{me.clearValue();}}}}}
me.collapse();me.callParent([e]);},createPicker:function(){var me=this,picker=me.callParent(arguments);if(me.pagingData){me.mon(picker,{'render':function(){me.getScrollEl(picker).on('scroll',me.onScroll,me);},scope:me});}
return picker;},onScroll:function(){var me=this,pa=$(me.getScrollEl().el.dom),paHeight=pa.height(),chHeight=pa.find('.cbo-content .ms-cbo-table-template').height();var store=me.getStore();if(store.getTotalCount()!==store.getCount()&&(pa.scrollTop()+paHeight)===chHeight){var recHighlightedItem=me.getRecordHighlightedItem(),overflowEl=me.picker.getOverflowEl(),scrollPos=overflowEl.getScroll();store.clearOnPageLoad=false;store.nextPage({params:this.getParams(this.lastQuery),callback:function(){store.clearOnPageLoad=true;if(recHighlightedItem){me.picker.clearHighlight();me.picker.navigationModel.setPosition(recHighlightedItem)}
overflowEl.setScrollTop(scrollPos.top);}});}},getScrollEl:function(picker){return Ext.get((picker||this.getPicker()).getTargetEl().parent().id);},onFieldMutation:function(e){var me=this,key=e.getKey(),isDelete=key===e.BACKSPACE||key===e.DELETE,rawValue=me.inputEl.dom.value,len=rawValue.length;if(key!==e.TAB){me.lastKey=key;if(len&&(e.type!=='keyup'||(!e.isSpecialKey()||isDelete))){me.doQueryTask.delay(me.queryDelay);}else{if(!len&&(!key||isDelete)){if(!me.multiSelect){me.value=null;me.displayTplData=undefined;}
me.collapse();if(me.queryFilter){me.changingFilters=true;me.store.removeFilter(me.queryFilter,true);me.changingFilters=false;}
delete me.lastQuery;}
me.callParent([e]);}}}});